# These are supported funding model platforms

github: [yuyenews]
patreon: yuyenews
open_collective: holmes-sherlocke
liberapay: sherlockholmes
custom: ['http://mars-framework.com/sponsor/sponsor.png']
