# These are supported funding model platforms

github: [yuyenews]
patreon: # yuyenews
ko_fi: sherlockholmes
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username

open_collective: sherlock-holmes
liberapay: sherlockholmes
custom: ['http://mars-framework.com/sponsor.html','https://www.paypal.me/yuye666']
